# Generated by Django 3.1.1 on 2020-09-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchID', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('emailAddress', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['branchID'],
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needID', models.IntegerField()),
                ('needStr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['needID'],
            },
        ),
        migrations.CreateModel(
            name='BranchNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodbank.branch')),
                ('need', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodbank.need')),
            ],
            options={
                'ordering': ['branchID'],
            },
        ),
    ]
