# Generated by Django 3.1.1 on 2020-09-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_ID']},
        ),
        migrations.AlterModelOptions(
            name='branchneed',
            options={'ordering': ['branch_ID']},
        ),
        migrations.AlterModelOptions(
            name='need',
            options={'ordering': ['need_ID']},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branchID',
            new_name='branch_ID',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='emailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='branchneed',
            old_name='branchID',
            new_name='branch_ID',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='needID',
            new_name='need_ID',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='needStr',
            new_name='need_str',
        ),
    ]
