# Generated by Django 3.1.1 on 2020-11-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0002_auto_20200913_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='province',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_info',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
