# Generated by Django 3.1.1 on 2020-11-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0003_auto_20201101_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
