# Generated by Django 3.1.1 on 2020-11-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0004_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_info',
            field=models.TextField(max_length=250),
        ),
    ]
