# Generated by Django 3.1.3 on 2021-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodbank', '0002_auto_20210113_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
